export enum TokenType {
  // () {}
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA,

  // KEYWORDS/COMMANDS
  LET, DATA, READ, RESTORE, DIM, IF, THEN, ELSE, END,
  WHILE, REPEAT, LOOP, GOTO, GOSUB, RETURN, ON, DEF,
  INPUT, PRINT, CRT, LOCK, RELEASE, UNTIL, STOP, CALL,

  // LITERALS
  IDENTIFIER, STRING, NUMBER, COMMENT

  // OPERATORS
  PLUS, MINUS, STAR, SLASH, CARROT, COLON, PLUS_EQ, 
  MIN_EQ, MUL_EQ, DIV_EQ, CONCAT_EQ, EQUALS, GREATER,
  GR_EQ, LESS, LE_EQ, SEMICOLON, 

  // SPECIAL CHARACTERS
  EOF


}