import { TokenType } from "./types";

export var KEYWORDS = new Map<string, TokenType>();

KEYWORDS.set("DATA", TokenType.DATA)
KEYWORDS.set("READ", TokenType.READ)
KEYWORDS.set("RESTORE", TokenType.RESTORE)
KEYWORDS.set("DIM", TokenType.DIM)
KEYWORDS.set("IF", TokenType.IF)
KEYWORDS.set("THEN", TokenType.THEN)
KEYWORDS.set("ELSE", TokenType.ELSE)
KEYWORDS.set("END", TokenType.END)
KEYWORDS.set("WHILE", TokenType.WHILE)
KEYWORDS.set("REPEAT", TokenType.REPEAT)
KEYWORDS.set("LOOP", TokenType.LOOP)
KEYWORDS.set("GOTO", TokenType.GOTO)
KEYWORDS.set("GOSUB", TokenType.GOSUB)
KEYWORDS.set("RETURN", TokenType.RETURN)
KEYWORDS.set("ON", TokenType.ON)
KEYWORDS.set("DEF", TokenType.DEF)
KEYWORDS.set("INPUT", TokenType.INPUT)
KEYWORDS.set("PRINT", TokenType.PRINT)
KEYWORDS.set("CRT", TokenType.CRT)
KEYWORDS.set("LOCK", TokenType.LOCK)
KEYWORDS.set("RELEASE", TokenType.RELEASE)
KEYWORDS.set("UNTIL", TokenType.UNTIL)
KEYWORDS.set("STOP", TokenType.STOP)
KEYWORDS.set("CALL", TokenType.CALL)
KEYWORDS.set("AND", TokenType.AND)